TABLE_(USER)
	STRING_(ID, 256) PRIMARY_KEY
	STRING_(PWD, 256)
	STRING_(MSG, 1024) NOT_NULL SQLDEFAULT("Já sem DEBIL!!!")
	STRING_(BGCOLOR, 32) NOT_NULL SQLDEFAULT("red")
	STRING_(FGCOLOR, 32) NOT_NULL SQLDEFAULT("white")
	STRING_(FCOLUMN, 32) NOT_NULL SQLDEFAULT("Debil")
END_TABLE

TABLE_(SESSION)
	STRING_ (SID, 32)       PRIMARY_KEY
	BLOB_   (SDATA)
	TIME_   (STIME)
END_TABLE

TABLE_(DATA)
	STRING_ (USER_ID, 100)
	TIME_   (DAY)           INDEX DUAL_UNIQUE(USER_ID, DAY)
	STRING_ (DESC, 1024) NOT_NULL SQLDEFAULT("")
END_TABLE
