TABLE_(USER)
	STRING_(ID, 256) PRIMARY_KEY
	STRING_(PWD, 256)
	STRING_(MSG, 1024) NOT_NULL SQLDEFAULT("Já sem DEBIL!!!")
	STRING_(BGCOLOR, 32) NOT_NULL SQLDEFAULT("red")
	STRING_(FGCOLOR, 32) NOT_NULL SQLDEFAULT("white")
	STRING_(FCOLUMN, 32) NOT_NULL SQLDEFAULT("Debil")
	STRING_(MSG2, 1024) NOT_NULL SQLDEFAULT("Já sem BOREC!!!")
	STRING_(BGCOLOR2, 32) NOT_NULL SQLDEFAULT("green")
	STRING_(FGCOLOR2, 32) NOT_NULL SQLDEFAULT("white")
	STRING_(FCOLUMN2, 32) NOT_NULL SQLDEFAULT("Borec")
END_TABLE

TABLE_(SESSION)
	STRING_ (SID, 32)       PRIMARY_KEY
	BLOB_   (SDATA)
	TIME_   (STIME)
END_TABLE

TABLE_(DATA)
	TIME_   (DAY) PRIMARY_KEY UNIQUE_LIST(DATA_INDEX, "USER_ID, DAY, EVENT")
	STRING_ (USER_ID, 100)
	STRING_ (EVENT, 1) NOT_NULL SQLDEFAULT("D")
	STRING_ (DESC, 1024) NOT_NULL SQLDEFAULT("")
END_TABLE

TABLE_(EVENTS)
	STRING_ (EVENT_ID, 1) NOT_NULL SQLDEFAULT("")
END_TABLE

// initialize with: insert into events values ("B"), ("D");
